const SERVER_CONFIGS = {
    GCP_PROJECT_ID: process.env.GCP_PROJECT_ID,
    GCLOUD_STORAGE_BUCKET: process.env.GCLOUD_STORAGE_BUCKET,
    OPENAI_MODEL: process.env.OPENAI_MODEL,
    OPENAI_TEMPERATURE: process.env.OPENAI_TEMPERATURE,
    OPENAI_MAX_TOKENS: process.env.OPENAI_MAX_TOKENS,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
}

export {
    SERVER_CONFIGS
}